# Generated by Django 3.0.6 on 2020-05-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cf_name', models.CharField(max_length=100)),
                ('cf_org', models.CharField(max_length=100)),
                ('cf_link', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Plateform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=70)),
                ('org_link', models.CharField(max_length=250)),
                ('org_image', models.ImageField(upload_to='home/images')),
            ],
        ),
    ]
