# Generated by Django 3.0.6 on 2020-05-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200514_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sk_name', models.CharField(max_length=100)),
                ('sk_type', models.CharField(max_length=50)),
            ],
        ),
    ]
