# Generated by Django 3.0.6 on 2020-05-15 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_myprojects_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprojects',
            name='project_type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
